### ISSUE TITLE
crash with maui net7 ?

### ISSUE THREAD

**Issue by softlion** [felipebaltazar/Maui.NeoControls#2]
![image](https://user-images.githubusercontent.com/190756/222973265-ab37d8fa-2b05-4956-9075-05e7deb8ddf9.png)

**Comment by felipebaltazar** [comment]
Hi @softlion !
Thanks for the report, can you provide a sample that reproduces this error?

**Comment by Petrarca181** [comment]
Same hare. Do you have any plans to  continue with this project? Looks very cool!
